name: Update Docs

on:
    push:
        branches:
            - deploy/web # Branch triggering the publish

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install BeyondJS globally
              run: npm install -g beyond@latest

            - name: Install project dependencies
              working-directory: docs
              run: npm install

            - name: Build package
              run: beyond build --pkg=pragmate-ui-docs --distribution=web --logs

            - name: Deploy to Netlify
              run: npx netlify-cli deploy --dir=docs/.beyond/builds/web/code --prod
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
